# Copyright 2021 pguimaraes
# See LICENSE file for licensing details.

options:
  kubeconfig:
    type: string
    default: ''
    description: |
      Used to issue commands against postgresql container. Pass it via base64:
      $ juju config postgresql kubeconfig="$(cat ~/.kube/config | base64 -w0)"
  admin_addresses:
    type: string
    default: ''
    description: |
      A comma-separated list of IP Addresses (or single IP) admin tools
      like pgAdmin3 will connect from. The IP addresses added here will
      be included in the pg_hba.conf file allowing ip connections to all
      databases on the server from the given IP addresses using md5
      password encryption. IP address ranges are also supported,
      using the standard format described in the PostgreSQL reference guide.
  ssl_cert:
    default: ''
    type: string
    description: |
      Certificate with CA certificate chain to be used in base64
      -----BEGIN CERTIFICATE-----
      <Primary cert in PEM format for your-domain>
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      <First intermediate CA certificate>
      -----END CERTIFICATE-----
      . . . . .
      (there may be more than one intermediate cert)
      . . . . .
      -----BEGIN CERTIFICATE-----
      <root-ca>
      -----END CERTIFICATE-----
      Pass the file with the certificate chain above as:
      $ juju config <your-charm> ssl_cert="$(cat <crt file> | base64 -w0)"
      Or in the bundle, using: include-base64://<path to crt file>
  ssl_key:
    default: ''
    type: string
    description: |
      Key to be used in base64
  extra_pg_auth:
    type: string
    default: ''
    description: |
      A extra pg_hba.conf auth rules. This will be included as-is into
      the pg_hba.conf file. Note that this should not be needed as db
      relations already create those rules the right way. Use this
      feature to allow clients to connect from outside the environment,
      or to configure replication between unrelated PostgreSQL services
      using the manual_replication option.
  extra_pg_conf:
    type: string
    description: |
      The defaults here match the defaults chosen by the charm,
      so removing them will not change them. They are listed
      as documentation. The charm actually loads the non-calculated
      defaults from this config.yaml file to make it unlikely it will
      get out of sync with reality.
      CERTIFICATES SUPPORT
      Avoid manually enabling SSL supportvia extra_pg_conf. Use ssl_cert
      and ssl_key options instead
    default: |
      listen_addresses='*'
      # log_timezone=UTC  Bug #1580331
      log_checkpoints=true
      log_connections=true
      log_disconnections=true
      log_autovacuum_min_duration=-1
      log_line_prefix='%t [%p]: [%l-1] db=%d,user=%u '
      archive_mode=on
      archive_command='/bin/true'
      hot_standby=true
      max_wal_senders=10
      # max_wal_senders=num_units * 2 + 5
      # wal_level=hot_standby (<9.4) or logical (>=9.4)
      # shared_buffers=total_ram*0.25
      # effective_cache_size=total_ram*0.75
      default_statistics_target=250
      from_collapse_limit=16
      join_collapse_limit=16
      wal_buffers=-1
      checkpoint_completion_target=0.9
      # password_encryption=true
      max_connections=100
